name: release
run-name: Release new tagged version
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "lirt/velero-plugin-for-openstack:${{ github.ref_name }}"
          file: "docker/Dockerfile"
          platforms: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
          no-cache: true
          build-args: |
            VERSION=${{ github.ref_name }}
            GIT_SHA=${{ github.sha }}
